-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.categories
(
    app_id integer NOT NULL,
    category character varying(250) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (app_id, category)
);

CREATE TABLE IF NOT EXISTS public.games
(
    app_id integer NOT NULL,
    name character varying COLLATE pg_catalog."default",
    release_date character varying COLLATE pg_catalog."default",
    estimated_owners character varying COLLATE pg_catalog."default",
    peak_ccu integer,
    required_age character varying COLLATE pg_catalog."default",
    price character varying COLLATE pg_catalog."default",
    discount character varying COLLATE pg_catalog."default",
    dlc_count integer,
    about character varying COLLATE pg_catalog."default",
    reviews character varying COLLATE pg_catalog."default",
    header_image character varying COLLATE pg_catalog."default",
    website character varying COLLATE pg_catalog."default",
    support_url character varying COLLATE pg_catalog."default",
    support_email character varying COLLATE pg_catalog."default",
    windows character varying COLLATE pg_catalog."default",
    mac character varying COLLATE pg_catalog."default",
    linux character varying COLLATE pg_catalog."default",
    metacritic_score character varying COLLATE pg_catalog."default",
    metacritic_url character varying COLLATE pg_catalog."default",
    user_score character varying COLLATE pg_catalog."default",
    positive character varying COLLATE pg_catalog."default",
    negative character varying COLLATE pg_catalog."default",
    score_rank character varying COLLATE pg_catalog."default",
    achievements character varying COLLATE pg_catalog."default",
    recommendations character varying COLLATE pg_catalog."default",
    notes character varying COLLATE pg_catalog."default",
    average_playtime_forever integer,
    average_playtime_two_weeks integer,
    median_playtime_forever integer,
    median_playtime_two_weeks integer,
    screenshots character varying COLLATE pg_catalog."default",
    movies character varying COLLATE pg_catalog."default",
    CONSTRAINT steam_data_pkey PRIMARY KEY (app_id)
);

CREATE TABLE IF NOT EXISTS public.genres
(
    app_id integer NOT NULL,
    genre character varying(250) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT genres_pkey PRIMARY KEY (app_id, genre)
);

CREATE TABLE IF NOT EXISTS public.developers
(
    app_id integer,
    developer character varying(250) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.publishers
(
    app_id integer,
    publisher character varying(250) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.supported_languages
(
    app_id integer,
    language text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.supported_audio_languages
(
    app_id integer,
    language text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.tags
(
    app_id integer NOT NULL,
    tag character varying(250) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tags_pkey PRIMARY KEY (app_id, tag)
);

ALTER TABLE IF EXISTS public.categories
    ADD CONSTRAINT categories_appid_fkey FOREIGN KEY (app_id)
    REFERENCES public.games (app_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.genres
    ADD CONSTRAINT genres_appid_fkey FOREIGN KEY (app_id)
    REFERENCES public.games (app_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.developers
    ADD CONSTRAINT fk_developers_appid FOREIGN KEY (app_id)
    REFERENCES public.games (app_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.publishers
    ADD CONSTRAINT fk_publishers_appid FOREIGN KEY (app_id)
    REFERENCES public.games (app_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.supported_languages
    ADD CONSTRAINT fk_supported_languages_appid FOREIGN KEY (app_id)
    REFERENCES public.games (app_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.supported_audio_languages
    ADD CONSTRAINT fk_supported_audio_languages_appid FOREIGN KEY (app_id)
    REFERENCES public.games (app_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tags
    ADD CONSTRAINT tags_appid_fkey FOREIGN KEY (app_id)
    REFERENCES public.games (app_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;